/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115582-gd55f5cba7b-20240606"
#endif /* AVUTIL_FFVERSION_H */
